# Generated by Django 4.0.6 on 2022-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
        migrations.AlterField(
            model_name='ministry',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
