# Generated by Django 4.0.6 on 2022-07-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_remove_member_photo_alter_ministry_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ministry',
        ),
        migrations.AddField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(to='church.member'),
        ),
    ]
