# Generated by Django 4.0.6 on 2022-07-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_remove_member_ministry_ministry_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='church.member'),
        ),
    ]
