# Generated by Django 4.0.6 on 2022-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
