# Generated by Django 4.0.6 on 2022-07-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_alter_member_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='ministry',
            field=models.ManyToManyField(blank=True, to='church.ministry'),
        ),
    ]
