# Generated by Django 4.0.6 on 2022-08-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_alter_ministry_options_remove_ministry_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'attendance'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['title'], 'verbose_name_plural': 'ministries'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member', to='church.member'),
        ),
    ]
